import { create } from "domain";

export const userCheckbyEmail = `SELECT * FROM "user" WHERE email = $1`;
 export const userSignup = `INSERT INTO "user" (name, email, password) VALUES($1,$2, $3) RETURNING *`;
 export const userLogin = `SELECT * FROM "user" WHERE email =$1`;
 export const generatePasswordResetLink = `UPDATE "user" SET reset_password_token =$1, reset_password_expire =to_timestamp($2) WHERE email = $3  `;
 export const fetchByToken = `SELECT * FROM "user" WHERE reset_password_token =$1 AND reset_password_expire > NOW()`; 
 export const updatePasswordByToken = `UPDATE "user" SET  reset_password_token = NULL, password=$1, reset_password_expire = NULL WHERE id =$2 RETURNING *`;
 export const profileUpdate = `UPDATE "user" SET name = $1, email = $2 WHERE id = $3 RETURNING *` ;
 export const productCreate = ` INSERT INTO products (name, description, stock, category, price, created_by,images, created_at ) VALUES ($1, $2, $3, $4, $5, $6, $7, NOW()) RETURNING*`;
 export const allProductsQuery = `SELECT * FROM products`
 export const sortByRating = `SELECT p.*, COUNT(r.*) AS review_count FROM products p LEFT JOIN reviews r ON p.id = r.product_id WHERE r.rating >= 4.1 GROUP BY p.id ORDER BY p.created_at DESC LIMIT 10`;
 export const sortByLatest = `SELECT p.*, COUNT(r.*) AS review_count FROM products p LEFT JOIN reviews r ON p.id = r.product_id WHERE p.created_at >=NOW() - INTERVAL '30 days' GROUP BY p.id ORDER BY p.created_at DESC LIMIT 10`;
 export const getProductById = `SELECT p.*, COUNT(r.*) AS review_count FROM products p LEFT JOIN reviews r ON p.id = r.product_id WHERE p.id = $1 GROUP BY p.id`;
 export const productUpdate = `UPDATE products SET name =$1, description =$2, stock = $3, category = $4, price = $5 WHERE id = $6 RETURNING*`;
 export const productDel = `DELETE FROM products WHERE id = $1 RETURNING*`;
 export const verifyProductById = `SELECT * FROM products WHERE id = $1`; 
 export const purchaseVerification = `SELECT oi.order_id FROM order_items oi JOIN orders o ON o.id = oi.order_id WHERE o.buyer_id=$1 AND oi.product_id=$2 AND o.order_status= 'Delivered' LIMIT 1`; 
 export const reviewsVerification = `SELECT r.* FROM reviews r JOIN order_items oi ON oi.product_id = r.product_id WHERE r.product_id=$1 AND oi.order_id= $2`;
 export const ratingPost = `INSERT INTO reviews (product_id, user_id, rating,comment,created_at) VALUES ($1,$2,$3,$4,NOW()) RETURNING*`;
 export const averageNumberRating= `SELECT AVG(rating) AS avg_rating FROM reviews WHERE product_id=$1`;
 export const ratingUpdate = `UPDATE products SET ratings = $1 WHERE id = $2 RETURNING*`;
 export const ratingDelete = `DELETE FROM reviews r USING order_items oi WHERE r.product_id= oi.product_id AND oi.order_id = $1 AND r.product_id = $2 RETURNING*`;
 export const userCountCheck = `SELECT COUNT(*) FROM "user" WHERE role = $1`;
 export const userCheckById = `SELECT * FROM "user" WHERE id = $1`;
 export const checkAllUsers = `SELECT * FROM "user" WHERE role = $1 LIMIT $2 OFFSET $3`;
 export const deleteUserById = `DELETE FROM "user" WHERE id =$1 RETURNING *`;
 export const totalRevenueQuery = `SELECT SUM(total_price) AS total_revenue FROM orders`;
 export const totalRevenueByDate = `SELECT SUM(total_price) AS total_revenue FROM orders WHERE DATE(created_at) > $1`;
 export const totalRevenueByDates = `SELECT SUM(total_price) AS total_revenue FROM orders WHERE DATE(created_at) BETWEEN $1 AND $2`;
 export const newUsersQuery = `SELECT * FROM "user" WHERE created_at >= $1 AND role = $2`;
 export const orderStatusQuery = `SELECT order_status, COUNT(*) FROM orders GROUP BY order_status`;
 export const monthlySalesQuery = `SELECT TO_CHAR(created_at, 'Mon YYYY') AS month, DATE_TRUNC('month', created_at) AS date, SUM(total_price) AS total_sales FROM orders GROUP BY date,month ORDER BY date ASC`;
 export const topSellingProductQuery = `SELECT p.*, COUNT(oi.product_id) AS product_count FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id ORDER BY product_count DESC LIMIT 5`;
 export const lowSellingProductQuery = `SELECT p.*, COUNT(oi.product_id) AS product_count FROM products p JOIN order_items oi ON p.id = oi.product_id GROUP BY p.id ORDER BY product_count ASC LIMIT 10`;
 export const lowStockProductQuery = `SELECT * FROM products WHERE stock <= 10`;
 export const lowRatedProductQuery = `SELECT * FROM products WHERE ratings <= 3.5`;
 export const topRatedProductsQuery = `SELECT * FROM products WHERE ratings > 4.5`;
 export const updatePaymentStatus = `UPDATE payments SET payment_status = $1 WHERE payment_intent_id = $2 RETURNING*`;
 export const updateOrderPaymentTime = `UPDATE orders SET paid_at = NOW() WHERE id = $1 RETURNING*`;
 export const fetchQuantityFromOrderItems = `SELECT product_id, quantity FROM order_items WHERE order_id = $1`;
 export const updateStockPostOrder = `UPDATE products SET stock = stock-$1 WHERE id = $2`;
 export const createPaymentIntent = `INSERT INTO payments (order_id, payment_type, payment_status, payment_intent_id) VALUES ($1, $2, $3, $4)`;
 export const getProductsByCategoryQuery = `SELECT * FROM products WHERE category = $1`;
export const getLiveOrdersQuery = `SELECT o.*, oi.*, p.* FROM orders`;
export const createOrderQuery = `INSERT INTO orders (buyer_id, total_price, tax_price, shipping_price) VALUES($1,$2,$3,$4) RETURNING*`;
export const createOrderItemsQuery = `INSERT INTO order_items (order_id, product_id, quantity, price, image, title) VALUES ($1, $2, $3, $4, $5, $6)`;
export const createShippingInfoQuery = `INSERT INTO shipping_info (order_id, full_name, state, city, country, address, pincode, phone) VALUES($1, $2, $3, $4, $5, $6, $7, $8)`;
export const getProductsByIdQuery = `SELECT * FROM products WHERE id = ANY($1 :: uuid[])`;
export const createPaymentQuery = `INSERT INTO payments (order_id, payment_type, payment_status) VALUES ($1, $2, $3)`;
export const getOrderbyIdQuery = `SELECT * FROM orders where id = $1`;
export const updatePaymentStatusFailedQuery = `UPDATE payments SET payment_status = $1 WHERE order_id = $2`;
export const updatePaymentIntentIdQuery = `UPDATE payments SET payment_intent_id = $1 WHERE order_id = $2`;
export const updatePaymentStatusPaidQuery = `UPDATE payments SET payment_status = $1 WHERE order_id = $2`;
export const updateOrderStatusAfterPaymentQuery = `UPDATE orders SET order_status = $1, paid_at = NOW() WHERE id = $2`;
export const updateOrderStatusAbandonedQuery = `UPDATE orders SET order_status = $1 WHERE id = $2`;
export const updateProductStockAfterOrderQuery = `UPDATE products SET stock = stock - oi.quantity FROM order_items oi WHERE products.id = oi.product_id AND oi.order_id = $1`;
export const getCountOrdersByBuyerIdQuery = `SELECT count(*) FROM orders WHERE buyer_id = $1 AND order_status IN ('Cancelled','Completed', 'Preparing','Packed','Placed')`;
export const getAllOrdersByBuyerIdQuery = `SELECT o.*, json_agg(json_build_object('item_id' , oi.id, 'quantity', oi.quantity, 'price', oi.price, 'product_id', oi.product_id, 'image', oi.image, 'name', p.name)) as order_items FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id WHERE o.buyer_id = $1 AND o.order_status IN ('Cancelled','Completed', 'Preparing','Packed','Placed') GROUP BY o.id ORDER BY o.created_at DESC LIMIT $2 OFFSET $3`;

export const getLiveOrdersCountQuery = `SELECT COUNT(*) FROM orders WHERE order_status IN ('Placed', 'Preparing', 'Packed')`;
export const getLiveOrdersDetailsQuery = `SELECT o.*, json_agg(json_build_object('item_id', oi.id, 'quantity', oi.quantity, 'price', oi.price, 'product_id', oi.product_id, 'image', oi.image, 'name', p.name)) as order_items, json_agg(json_build_object('name', s.full_name, 'address', s.address, 'contact_info', s.phone)) as shipping_info FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id JOIN shipping_info s ON s.order_id = o.id WHERE o.order_status IN ('Placed', 'Preparing', 'Packed') GROUP BY o.id`;
export const getLiveOrderByIdQuery = `SELECT o.*, json_agg(json_build_object('item_id', oi.id, 'quantity', oi.quantity, 'price', oi.price, 'product_id', oi.product_id, 'image', oi.image, 'name', p.name)) as order_items, json_agg(json_build_object('name', s.full_name, 'address', s.address, 'contact_info', s.phone)) as shipping_info FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id JOIN shipping_info s ON s.order_id = o.id WHERE o.id = $1 AND o.order_status IN ('Placed', 'Preparing', 'Packed') GROUP BY o.id`;
export const updateOrderStatusPreparingQuery = `UPDATE orders SET order_status = $1, expected_delivery_at = NOW() + ($2 * INTERVAL '1 minute'), accepted_at = NOW(), accepted_by_id = $3 WHERE id = $4 RETURNING *`;
export const updateOrderStatusPackedQuery = `UPDATE orders SET order_status = $1, packed_at = NOW() WHERE id = $2 RETURNING *`;
export const updateOrderStatusCompletedQuery = `UPDATE orders SET order_status = $1, completed_at = NOW() WHERE id = $2 RETURNING *`;
export const updateOrderStatusDefaultQuery = `UPDATE orders SET order_status = $1 WHERE id = $2 RETURNING *`;
export const getCompletedOrdersTodayCountQuery = `SELECT COUNT(*) FROM orders WHERE DATE(completed_at) = CURRENT_DATE AND order_status IN ('Completed')`;
export const getCompletedOrdersByIdQuery = `SELECT o.*, json_agg(json_build_object('item_id', oi.id, 'quantity', oi.quantity, 'price', oi.price, 'product_id', oi.product_id, 'image', oi.image, 'name', p.name)) as order_items, json_agg(json_build_object('name', s.full_name, 'address', s.address, 'contact_info', s.phone)) as shipping_info FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id JOIN shipping_info s ON s.order_id = o.id WHERE RIGHT(o.id::text, 8) =$1 AND o.order_status IN ('Cancelled', 'Abandoned', 'Completed') GROUP BY o.id ORDER BY o.created_at DESC LIMIT $2 OFFSET $3`;
export const getCompletedOrdersByPhoneQuery = `SELECT o.*, json_agg(json_build_object('item_id', oi.id, 'quantity', oi.quantity, 'price', oi.price, 'product_id', oi.product_id, 'image', oi.image, 'name', p.name)) as order_items, json_agg(json_build_object('name', s.full_name, 'address', s.address, 'contact_info', s.phone)) as shipping_info FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id JOIN shipping_info s ON s.order_id = o.id WHERE s.phone =$1 AND o.order_status IN ('Cancelled', 'Abandoned', 'Completed') GROUP BY o.id ORDER BY o.created_at DESC LIMIT $2 OFFSET $3`;
export const getCompletedOrdersAllQuery = `SELECT o.*, json_agg(json_build_object('item_id', oi.id, 'quantity', oi.quantity, 'price', oi.price, 'product_id', oi.product_id, 'image', oi.image, 'name', p.name)) as order_items, json_agg(json_build_object('name', s.full_name, 'address', s.address, 'contact_info', s.phone)) as shipping_info FROM orders o JOIN order_items oi ON oi.order_id = o.id JOIN products p ON oi.product_id = p.id JOIN shipping_info s ON s.order_id = o.id WHERE o.order_status IN ('Cancelled', 'Abandoned', 'Completed') GROUP BY o.id ORDER BY o.created_at DESC LIMIT $1 OFFSET $2`;